### PR TITLE
feat:add encryption and decryption capabilities for content

### PR DESCRIPTION
**Pull request by D3PSI**

### CODE REVIEW

**Comment by D3PSI** [comment]
TODO: use same nonce for encryption and decryption

**Comment by D3PSI** [comment]
current state of things: we finally have a working clang installation on our heroku, so that issue is resolved. however, we still cannot seem to build reliably as sometimes the build gets stuck when installing dependencies.

**Comment by D3PSI** [comment]
> current state of things: we finally have a working clang installation on our heroku, so that issue is resolved. however, we still cannot seem to build reliably as sometimes the build gets stuck when installing dependencies.

i guess we'll see how that situation develops, i don't think there is anything i can do about that right now

**Comment by D3PSI** [comment]
yeah, these build are highly unpredictable, i don't know what to think here

**Comment by D3PSI** [comment]
open points: 
- we need to see how we deal with the padding generated by the encryption process when decrypting

**Review by ReddixT — APPROVED** [review]

**Pull request merged**
