### PR TITLE
refactor(frontend):start anew

### PR DESCRIPTION
**Pull request by D3PSI**

### CODE REVIEW

**Comment by D3PSI** [comment]
@ReddixT the idea here will be to define unified interfaces in the frontend to display things like notifications, warnings and such. we will start creating a component library of reusable components, so that we don't have to style things individually everywhere

**Review by D3PSI — COMMENTED** [review]
looks good, but i think we should name the route 'reset' instead of 'reset-password' @ReddixT

**Comment by ReddixT** [comment]
> looks good, but i think we should name the route 'reset' instead of 'reset-password' @ReddixT 

Supertoken sends a link with the page "reset-password" so we would then have to make 2 pages. But reset-password is with these circumstances definitely needed.

**Comment by D3PSI** [comment]
ah, that's why. fair enough. let's leave it then :+1:

**Comment by ReddixT** [comment]
> @ReddixT wait, do we now have two authenticators? one in `src/components/security` and one in `src/components/authenticator`

my mistake haven't removed the other folder yet, it's removed now

**Comment by D3PSI** [comment]
@reddixt, good work, only two things: we should always explicitely declare react components as react function components by giving them the `React.Fc<T>` type. otherwise, while compiling we can run into issues.

the other thing is that we should not have things like the `useEnter` hook, as symbols starting with `use...` have a special meaning in react. what we now have is this:

for event handling and such it is most likely more declarative and readable if we just keep the logic inside the page/component that uses it :)

but i have to say, the fact that you're trying these things is testament to the fact that you're starting to think about `the bigger picture` and is great to see :)

**Comment by D3PSI** [comment]
alright, good stuff that. i would approve this PR, but since I created it GitHub won't let me

**Comment by D3PSI** [comment]
this is beginning to look great. should we merge this PR so that this one doesn't get bigger and bigger forever?

**Comment by ReddixT** [comment]
> this is beginning to look great. should we merge this PR so that this one doesn't get bigger and bigger forever?

yeah i think the core features we had added before are implemented so we should merge this pr

**Pull request merged**
